apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: containor name
  namespace: cvat
  annotations:
    nuclio.io/project-name: cvat
    name: "YOLOv8"
    type: "detector"
    framework: "ultralytics"
  
    spec: |
     [
        { "id": 0, "name": "class_1" }
      ]

spec:
  description: YOLOv8- Auto_Annotation 
  runtime: python:3.9
  handler: main:infer
  eventTimeout: 120s
  readinessTimeoutSeconds: 120

  build:
    image: cvat/nuclio/containor name
    baseImage: python:3.9
    
    directives:
      preCopy:
        - kind: USER
          value: root
        - kind: RUN
          value: apt-get update && apt-get install -y libgl1 libglib2.0-0 libsm6 libxrender1 libxext6
        - kind: WORKDIR
          value: /opt/nuclio
        - kind: RUN
          value: pip install ultralytics opencv-python-headless numpy pillow

  triggers:
    myHttpTrigger:
      maxWorkers: 1
      kind: "http"
